# Generated by Django 3.1.5 on 2021-02-01 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_companyprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='prerequisite',
            field=models.CharField(max_length=1000000, null=True),
        ),
    ]
