# Generated by Django 2.2.19 on 2021-03-12 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20210311_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companyprofile',
            name='internship_duration',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='internship_position',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='minimum_cgpa',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='prerequisite',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='stipend',
        ),
        migrations.RemoveField(
            model_name='companyprofile',
            name='students_required',
        ),
    ]
