# Generated by Django 2.2.19 on 2021-03-12 20:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0010_studentregistration_result_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stipend', models.FloatField(default=0, null=True)),
                ('internship_duration', models.IntegerField(default=0, null=True)),
                ('students_required', models.IntegerField(default=0, null=True)),
                ('internship_position', models.CharField(max_length=100, null=True)),
                ('minimum_cgpa', models.FloatField(default=5.0, null=True)),
                ('prerequisite', models.CharField(max_length=1000000, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
