# Generated by Django 2.2.19 on 2021-03-10 19:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_companyannouncement_round_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
