# Generated by Django 2.2.19 on 2021-03-12 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_studentregistration'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
