# Generated by Django 2.2.19 on 2021-03-12 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_companyannouncement_internship'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='internship_name',
            field=models.CharField(max_length=10000, null=True),
        ),
    ]
