# Generated by Django 2.2.19 on 2021-03-21 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20210314_1833'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyannouncement',
            name='last_round',
            field=models.BooleanField(default=False),
        ),
    ]
