# Generated by Django 2.2.19 on 2021-03-22 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0028_staffpermissions_can_delete_staff_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermissions',
            name='can_unban_users',
            field=models.BooleanField(default=False),
        ),
    ]
