# Generated by Django 2.2.19 on 2021-03-22 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='topic',
            new_name='title',
        ),
    ]
