# Generated by Django 2.2.19 on 2021-03-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0035_auto_20210323_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentregistration',
            name='my_action',
            field=models.IntegerField(default=0),
        ),
    ]
