# Generated by Django 2.2.19 on 2021-03-25 00:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0039_auto_20210324_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='date',
        ),
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='answer',
            field=models.TextField(default=100000000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='date_of_answer',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 13, 2, 788638)),
        ),
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='date_of_question',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 13, 2, 788615)),
        ),
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='support_responder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_responder', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 13, 2, 785016)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 13, 2, 784964)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 13, 2, 789352)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 13, 2, 787086)),
        ),
        migrations.DeleteModel(
            name='TechnicalSupportResponse',
        ),
    ]
