# Generated by Django 2.2.19 on 2021-03-25 00:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0040_auto_20210325_0013'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalsupportrequest',
            old_name='previous_support_id',
            new_name='main_support_id',
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 14, 30, 540386)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 14, 30, 540364)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 14, 30, 544105)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 14, 30, 541711)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_answer',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 14, 30, 543507)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_question',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 0, 14, 30, 543484)),
        ),
    ]
