# Generated by Django 2.2.19 on 2021-03-25 01:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0041_auto_20210325_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='responder_started',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 32, 13, 87576)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 32, 13, 87540)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 32, 13, 92812)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 32, 13, 89488)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_answer',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 32, 13, 91871)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_question',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 32, 13, 91839)),
        ),
    ]
