# Generated by Django 2.2.19 on 2021-03-25 01:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0042_auto_20210325_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='requester_ended',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 47, 36, 487604)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 47, 36, 487581)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 47, 36, 491010)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 47, 36, 488834)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_answer',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 47, 36, 490402)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_question',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 47, 36, 490383)),
        ),
    ]
