# Generated by Django 2.2.19 on 2021-03-25 01:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0043_auto_20210325_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 53, 46, 921594)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 53, 46, 921572)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 53, 46, 925124)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 53, 46, 922788)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_answer',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 53, 46, 924308)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date_of_question',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 1, 53, 46, 924289)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='requester_ended',
            field=models.BooleanField(default=False),
        ),
    ]
