# Generated by Django 2.2.19 on 2021-03-25 02:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0044_auto_20210325_0153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technicalsupportrequest',
            old_name='answer',
            new_name='message',
        ),
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='date_of_answer',
        ),
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='date_of_question',
        ),
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='question',
        ),
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 45, 24, 142467)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 45, 24, 139554)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 45, 24, 139531)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 45, 24, 143044)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 45, 24, 140941)),
        ),
    ]
