# Generated by Django 2.2.19 on 2021-03-25 02:51

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0045_auto_20210325_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='requester_ended',
        ),
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='responded',
        ),
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='responder_started',
        ),
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='support_requester',
        ),
        migrations.RemoveField(
            model_name='technicalsupportrequest',
            name='support_responder',
        ),
        migrations.AddField(
            model_name='technicalsupportrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 51, 51, 438149)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 51, 51, 438110)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 51, 51, 441457)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 51, 51, 439520)),
        ),
        migrations.AlterField(
            model_name='technicalsupportrequest',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 2, 51, 51, 440957)),
        ),
    ]
