# Generated by Django 2.2.19 on 2021-03-25 13:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0047_auto_20210325_0307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profilevisibilty',
            name='to_company',
        ),
        migrations.RemoveField(
            model_name='profilevisibilty',
            name='to_other_student',
        ),
        migrations.AddField(
            model_name='profilevisibilty',
            name='to_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilevisibilty',
            name='to_all_companies',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilevisibilty',
            name='to_all_students',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profilevisibilty',
            name='to_registered_companies',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 35, 59, 747128)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 35, 59, 747105)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 35, 59, 750412)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 25, 13, 35, 59, 748360)),
        ),
    ]
