# Generated by Django 2.2.19 on 2021-03-27 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0052_auto_20210326_1054'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='date_of_announcement',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 21, 35, 13, 788097)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 21, 35, 13, 788066)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 21, 35, 13, 792433)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 3, 27, 21, 35, 13, 789529)),
        ),
    ]
