# Generated by Django 3.0.8 on 2021-05-03 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0056_auto_20210327_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffpermissions',
            name='can_activate_session',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='announcement_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 19, 8, 51, 827073)),
        ),
        migrations.AlterField(
            model_name='companyannouncement',
            name='last_date_to_apply',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 19, 8, 51, 827040)),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 19, 8, 51, 830485)),
        ),
        migrations.AlterField(
            model_name='studentregistration',
            name='date_of_registrations',
            field=models.DateTimeField(default=datetime.datetime(2021, 5, 3, 19, 8, 51, 828262)),
        ),
    ]
