# Generated by Django 3.1.5 on 2021-01-31 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_studentprofile_otp_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='otp',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
