# Generated by Django 3.1.6 on 2021-03-02 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20210205_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='image',
            field=models.ImageField(default='static/dashbaord/img/us_ma.png', upload_to='post_images/'),
        ),
    ]
