# Generated by Django 3.1.5 on 2021-03-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210302_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='image',
            field=models.ImageField(default='us_ma.png', upload_to='post_images/'),
        ),
    ]
