# Generated by Django 2.2.19 on 2021-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_companyprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='cgpa',
            field=models.IntegerField(default=0),
        ),
    ]
