# Generated by Django 3.1.5 on 2021-01-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='otp_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
